### ISSUE TITLE
Can lab results outside of the 11 common measure categories be populated?

### ISSUE THREAD

**Issue by rusincovitch** [CDMFORUM/CDM-GUIDANCE#18]
A consideration discussed in the PCORnet Common Data Model workgroup meeting this afternoon was:

There are 11 "common measures" classified by the LAB_NAME field (such as hemoglobin a1C, creatinine, etc).

**But what about lab results records that aren't part of the common measures?** @rhessmd suggests the lab result for **fasting plasma glucose** is a desirable measure for the bariatric study, and is an example of this scenario.

Shelley suggests that lab results outside of the 11 common measures can be loaded into the LAB_RESULT_CM table as specified, but that to identify the category of lab result for analysis, a LOINC code would likely be a very important factor.

The workgroup suggests that more specific guidance to this permissibility would be valuable.

With many thanks to @rhessmd who provided this use case, and with key perspective from @mmatheny!

**Comment by mgkahn** [comment]
I would think we'd need to think about four very different scenarios:

1. Additions to the 11 common measures as defined in the formal PCORnet CDM that are expected to be required for CDM conformance
2. Additions that are driven by a PCORnet-approved project that are required to participate in the project
3. Additions that are driven by a project by an informal cabal of PCORnet sites
4. Additions that are driven by the members of a CDRN/PPRN only (such as PEDSnet)

Just like the Data Quality WG conversations, these distinctions are important because they impact different size of resources and come from different governance models.

**Comment by rusincovitch** [comment]
This item has been incorporated into draft v3.0 Implementation Guidance, part of the PCORnet-wide open feedback cycle on Data Characterization (September 19-30, 2016): [https://pcornet.imeetcentral.com/p/aQAAAAAC1YDb](https://pcornet.imeetcentral.com/p/aQAAAAAC1YDb)
