### ISSUE TITLE
Dose and Units for PRESCRIBING table

### ISSUE THREAD

**Issue by rusincovitch** [CDMFORUM/CDM-GUIDANCE#4]
As reported by @smerek: A network raised the issue that there are no fields in the PRESCRIBING table (CDM v3.0) for "dose" and "units."

Issue is created for future assessment of feasibility and harmonization of adding this data to the PRESCRIBING table.

Network was encouraged to include this data in their localized implementation of CDM, per guiding principle #8.

**Comment by rusincovitch** [comment]
I was reminded of this issue during my sessions here at the NLM Georgia biomedical informatics course.

Just to check in: RxNorm embeds the dose and unit into the record directly (eg, asprin 80 mg is a different **record** than aspirin 325 mg). This was part of our consideration in the table design with the CDM.

However, if the site does not use RxNorm, I can see where this might be a concern and should be considered (both as guidance and potential enhancement).

**Comment by smerek** [comment]
It depends on which term type is captured in the source data.  If the RxCUI is recorded for term type "ingredient" then no dose/unit information is included, because it's not specific to this level of granularity.  For example, the RxCUI for lisinopril (term type: ingredient) is 29046.  The RxCUI for lisinopril 10 mg (term type: clinical drug component) is 316151.

**Comment by rusincovitch** [comment]
This is a great example - thank you! 

I'm having a bit of trouble thinking of a use case where we would need dose and unit as separate elements, given that source data at the ingredient level seems unlikely to be combined with the precision of a dose/unit? But this may be so dependent on mapping practices as well - I may be thinking of it wrong!

Could we ask the med mapping interest group about their experiences/thoughts this topic at the next meeting?

**Comment by smerek** [comment]
That is a great idea; I will put it on my radar for the med group.  I am interested to know if sites would code their meds at the ingredient level, and also have dose/unit information.  They must have dose/unit information in their prescribing data!  (It may be that coding to the ingredient level RxCUI is easier, so that's as far as they take it?)
