### ISSUE TITLE
Assess RX_QUANTITY_UNIT field

### ISSUE THREAD

**Issue by smerek** [CDMFORUM/CDM-GUIDANCE#40]
Need to review the value set for potential revision.  ("Pill" and "tablet" are included in the value set but "capsule" is not.  What is best mapping for "capsule?")

List of NDC dosage form terms attached for consideration/reference.
[NDC_DosageForm.xlsx](https://github.com/CDMFORUM/CDM-GUIDANCE/files/1068457/NDC_DosageForm.xlsx)

RxNorm dose forms (for reference) located here: https://www.nlm.nih.gov/research/umls/rxnorm/docs/2012/appendix2.html

**Comment by smerek** [comment]
Additional input from a data partner attempting to parse RX_QUANTITY_UNIT from RxNORM string information:

**Code used to associate source value to CDM value:**
where (upper(c_name) like '%PILL%'
or upper(c_name) like '%CAPSULE%' --equiv to PILL
or upper(c_name) like '%TABLET%' = Tablet
or upper(c_name) like '%VIAL%' = Vial
or upper(c_name) like '%SOLUTION%' = Solution
or upper(c_name) like '%SYRINGE%' --equiv to SOLUTION
or upper(c_name) like '%CATRIDGE%' --equiv to SOLUTION
or upper(c_name) like '%SYRUP%' --equiv to SOLUTION
or upper(c_name) like '%ELIXIR%' --equiv to SOLUTION
or upper(c_name) like '%SUSPENSION%' = Suspension
or upper(c_name) like '%OINTMENT%' = Ointment
or upper(c_name) like '%TOPICAL LOTION%' -- equiv to OINTMENT
or upper(c_name) like '%TOPICAL SPRAY%' -- equiv to OINTMENT
or upper(c_name) like '%TOPICAL GEL%' -- equiv to OINTMENT
or upper(c_name) like '%TOPICAL FOAM%' -- equiv to OINTMENT
or upper(c_name) like '%CREAM%' = Cream
or upper(c_name) like '%POWDER%' = Powder
or upper(c_name) like '%PATCH%' = Patch
or upper(c_name) like '%INHALER%' = Inhaler
or upper(c_name) like '%INHALANT%' -- equiv to INHALER
or upper(c_name) like '%KIT%' = Kit
or upper(c_name) like '%DEVICE%' = Device
or upper(c_name) like '%AUTO-INJECTOR%' -- equiv to DEVICE
or upper(c_name) like '%APPLICATOR%' -- equiv to DEVICE
or upper(c_name) like '%IMPLANT%' -- equiv to DEVICE

**Additional values in source data that don't have a clear match to CDM value; assign to "OT?"**
chewing gum, lozenge, suppository, oral strip, pad, oral gel, 
mouthwash, shampoo, soap, eye drops, ophthalmic gel, oral paste

**Comment by cborromeo** [comment]
Thanks for promoting this question Michelle.  This question came from my CDRN, PaTH.  When PaTH initially looked at the RX_QUANTITY_UNIT column, we could not determine the source behind this column.  The CDM 3.1 "Data Element Provenance" column says it comes from NDC attributes which appears to be misleading.  Based on Michelle's feedback, it appears to loosely correlate to the RxNORM dosage formats.  Therefore, we should extract these values directly from RxNORM instead of utilizing the text parsing approach I initially created.  The REST API for RxNORM allows us to extract the data using this type of call:

https://rxnav.nlm.nih.gov/REST/rxcui/[RxNORM CUI]/related?tty=DF

where [RxNORM CUI] is replaced with an RxNORM CUI like 370588 and DF is the "dosage form".  I can build a map of the RxNORM CUIs and their corresponding dosage forms.  However, there is still no one-to-one mapping from the dosage form shown on https://www.nlm.nih.gov/research/umls/rxnorm/docs/2012/appendix2.html and the CDM 3.1 documentation.  I think the CDM should be modified to remove this ambiguity.  

I like to propose the following steps, please let me know if this is advisable:

1.  for each RxNORM code, return the dosage form string (Oral Tablet, Oral Suspension, etc.)
2.  Compare the dosage form string (ex: "oral tablet") against the hierarchy shown in       https://www.nlm.nih.gov/research/umls/rxnorm/docs/2012/appendix2.html.
3.  Match the  "oral tablet" to its higher level term (ex: tablet) and return that higher level term as the contents for the RX_QUANTITY_UNIT column for this drug.

If this seems acceptable, then the CDM should match the higher level items listed in the RxNORM Appendix 2 (the higher level terms are shown as unbolded).  There are several higher level terms missing from the CDM (ex: inhalents, spray, foam, bar, etc.).  We need to make the mapping very clear otherwise each CDRN may have their own mapping process.

**Comment by smerek** [comment]
RxNorm value set incorporated into CDM v4.0.
