### ISSUE TITLE
LAB_RESULT_CM -  CDMv3.1 all results - RESULT_UNIT, SPECIMEN_SOURCE lack guidance. 

### ISSUE THREAD

**Issue by astoddard** [CDMFORUM/CDM-GUIDANCE#42]
The request to load all lab results in CDMv3.1 means many labs will have RESULT_UNITs and SPECIMEN_SOURCES outside of the set defined for the limited lab set for CDMv3.0.

The most current guidance document known to me is:
"2017-05-01_Integrated-CDM-Specification-Implemeantion-Guidance-CDM-v... .pdf" 

Both SPECIMEN_SOURCES and RESULT_UNIT comments in this document contain language "Please see the Implementation Guidance for additional details (description updated in v3.1).", but I can find none.

When addition lab types have sources and units falling outside of the 3.0 defined lists should these fields be set to "OT" (and the true source data captured in additional raw columns if a site so chooses - otherwise the specific units and source would be lost) ? 

Should RESULT_UNIT be 'NI' for qualitative results?

Question for future discussion - Can future versions consider obsoleting these mappings and using the LOINC defined systems and units as the approved vocabulary?

**Comment by smerek** [comment]
Hi Alex.  Thank you for posting these great questions.
There is no additional field-level guidance for those two fields, and you have the most current version of the integrated specification-implementation guidance document.  A couple thoughts:

-Choosing "OT" for SPECIMEN_SOURCE values other than those in the current value set makes complete sense.
-RESULT_UNIT for qualitative results can just be left blank, since that field does not have a value set.

I will create an issue ticket to explore your suggestions for future discussion.

**Comment by astoddard** [comment]
Hi Michelle,

Thank you for your very fast response.

RESULT_UNIT seem to  have a sort-of value set in "Implementation Guidance Reference Table 3: Laboratory Standard Abbreviations" (pages 62 & 63 of 102 in the guidance). And these are somewhat assessed in the test LAB_L3_NAME_RUNIT  in the data characterization. (Although this test can not work for the other labs which don't have LAB_NAMEs defined).

Table 3 does list "OT" which is why I wondered about it and if it is an exclusive set. If RESULT_UNIT is not restricted to Table 3, am I free to put all relevant units for the additional lab tests in that field?

**Comment by smerek** [comment]
Hi Alex.
The values you enter into the RESULT_UNIT field are not restricted to those included in Reference Table 3; it's just meant to be a list of common result unit words, and how to abbreviate them in a standardized representation.
You have highlighted something that we need to look into further, which is why "NI," "UN," and "OT" are included in this table.  For now, please just use these standard abbreviations if applicable to your RESULT_UNIT values, e.g., if the value in your source data is "unknown" use the abbreviation "UN."  We will continue discussing whether to keep these in Reference Table 3 going forward.

**Comment by astoddard** [comment]
Thank you, Michelle.

We will face a lot of standardization issues around units for lab tests in the large (my source system data is ghastly on its own). We will make a best reasonable effort for the initial 3.1 load and use the UCUM units of measurement as suggested by LOINC where we can.

See: (https://loinc.org/usage/units/)
(https://loinc.org/download/common-ucum-pdf/)
(http://unitsofmeasure.org/ucum.html)

**Comment by smerek** [comment]
New value set for RESULT_UNIT added in CDM v4.0.
