### ISSUE TITLE
Mapping between CMS Place of Service and FACILITY_TYPE

### ISSUE THREAD

**Issue by kmarsolo** [CDMFORUM/CDM-GUIDANCE#67]
The attached file contains an initial mapping between the CMS Place of Service Code Set (https://www.cms.gov/Medicare/Coding/place-of-service-codes/Place_of_Service_Code_Set.html) and the FACILITY_TYPE valueset used in CDM v4.0.  

This mapping may be updated over time.
[Place_of_Service-Facility_Type-2018_04_24.xlsx](https://github.com/CDMFORUM/CDM-GUIDANCE/files/1948357/Place_of_Service-Facility_Type-2018_04_24.xlsx)

**Comment by don-torok** [comment]
Value in Mapping between CMS Place of Service and FACILITY_TYPE has:
'FEE_FOR _SERVICE_PRIVATE_PHYSICIANS_GROUP_OFFICE'
 Value in ValueSet_ReferenceFile_v1.2.xlsx:
'FEE _FOR _SERVICE_PRIVATE_PHYSICIANS_GROUP_OFFICE'

Note the Space after 'FEE' in the second value.  We got dinged for **Required fields contain values outside of data model specifications	Data Model Conformance** because of this difference.

Suggest removing spaces from entries in ValueSet_ReferenceFile_v1.2.xlsx so that there are just underscores between words.

**Comment by kmarsolo** [comment]
Don - yes, this was updated as of v1.3.  There were a few other values with extra spaces.  Those have been fixed as well.
