### ISSUE TITLE
Disability-related data elements

### ISSUE THREAD

**Issue by rusincovitch** [CDMFORUM/CDM-GUIDANCE#7]
Russell Rothman suggested that many EHRs have adopted the 6 minimum recommended questions about disability from HHS in anticipation of meaningful use requirements. 

Reference: [US Health and Human Services (HHS) implementation guidance (October 2011), section III.D.](https://aspe.hhs.gov/basic-report/hhs-implementation-guidance-data-collection-standards-race-ethnicity-sex-primary-language-and-disability-status#III)

This area is expected to have synergy with work by Romana Hasnain-Wynia and the PCORI Disparities Panel.

**Comment by rusincovitch** [comment]
For more information, please see the [entry on Guidance for Potential CDM Enhancements](https://github.com/PCORnet/DataCommittee/wiki/Guidance-for-Potential-CDM-Enhancements) in the PCORnet Data Committee wiki.

**Comment by smerek** [comment]
From HHS implementation guidance:
D. DISABILITY STATUS

The six item set of questions used on ACS and other major surveys to gauge disability is the data standard for survey questions on disability. Note the age thresholds for survey participants for the different disability questions.

Data Standard for Disability Status
1. Are you deaf or do you have serious difficulty hearing? a. ____ Yes b. ____ No
2. Are you blind or do you have serious difficulty seeing, even when wearing glasses? a. ____ Yes b.____No 3. Because of a physical, mental, or emotional condition, do you have serious difficulty concentrating, remembering, or making decisions? (5 years old or older) a. ____Yes b. ____No
4. Do you have serious difficulty walking or climbing stairs? (5 years old or older) a. ____Yes b. ____No
5. Do you have difficulty dressing or bathing? (5 years old or older) a. ____Yes b. ____ No
6. Because of a physical, mental, or emotional condition, do you have difficulty doing errands alone such as visiting a doctor's office or shopping? (15 years old or older) a. ____Yes b. ____ No

The six-item disability standard represents a minimum standard and the questions and answer categories cannot be changed. Additional questions on disability may be added to any survey as long as the minimum standard is included. If the ACS changes the disability questions in the future, HHS will revisit the standard and modify as necessary.

**Comment by smerek** [comment]
Disability information and assistance needed panel [HHS.ACA Section 4302.ONC] is included in the LOINC terminology, so this data can be included in the PRO table, effective CDM v4.0.
