### ISSUE TITLE
RX_FREQUENCY

### ISSUE THREAD

**Issue by marcyharris** [CDMFORUM/CDM-GUIDANCE#77]
The value set code 9, "as needed (PRN) was dropped from the CDM 4.1 specification document.  Assuming it actually continues to exist, just a document editing issue.

**Comment by kmarsolo** [comment]
This is by design.  We created the RX_PRN_FLAG field for PRN medications.  This allows RX_FREQUENCY to be used for more specific frequency instructions.

Keith



On Jul 31, 2018, at 5:04 PM, marcyharris <notifications@github.com<mailto:notifications@github.com>> wrote:


The value set code 9, "as needed (PRN) was dropped from the CDM 4.1 specification document. Assuming it actually continues to exist, just a document editing issue.
